# Config for CustomKit <Xeon>
Version: 1.0.0
# CustomKit would work normally if you disable Money which means your players dont need to buy a kit!
Money: true
# Price for Infinity Kit
Infinity: 1500
# Price for Legendary Kit
Legendary: 1500
